import { arrayOf, objectSchema } from "./openapiHelpers";

export const notmidOpenApiSchemas = {
  HealthResponse: objectSchema({
    ok: { type: "boolean" },
    requestId: { type: "string" },
    service: { type: "string" },
    mode: { $ref: "#/components/schemas/NotmidAuthMode" },
  }),
  NotmidSource: { type: "string", enum: ["fixture", "api", "cache"] },
  NotmidAuthMode: { type: "string", enum: ["fake", "firebase", "disabled"] },
  NotmidAuthProvider: { type: "string", enum: ["fake", "anonymous", "google"] },
  NotmidAuthIntent: { type: "string", enum: ["browse", "capture", "chat", "profile"] },
  NotmidAuthRequirement: {
    type: "string",
    enum: ["capture", "save", "chat", "profile-edit", "moderation"],
  },
  NotmidCaptureVisibility: { type: "string", enum: ["public", "friends", "private"] },
  NotmidMetricSet: objectSchema({
    likes: { type: "number" },
    saves: { type: "number" },
    comments: { type: "number" },
    distanceLabel: { type: "string" },
  }),
  NotmidPlace: objectSchema({
    id: { type: "string" },
    name: { type: "string" },
    neighborhood: { type: "string" },
    category: { type: "string" },
    address: { type: "string" },
    lat: { type: "number" },
    lng: { type: "number" },
    openNow: { type: "boolean" },
    score: { type: "number" },
    receiptCount: { type: "number" },
    coverImageUrl: { type: "string" },
  }),
  NotmidClip: objectSchema({
    id: { type: "string" },
    title: { type: "string" },
    caption: { type: "string" },
    creatorHandle: { type: "string" },
    placeId: { type: "string" },
    moodTags: arrayOf({ type: "string" }),
    capturedAtLabel: { type: "string" },
    coverImageUrl: { type: "string" },
    videoUrl: { type: "string" },
    metrics: { $ref: "#/components/schemas/NotmidMetricSet" },
  }),
  NotmidClipSaveResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    clip: { $ref: "#/components/schemas/NotmidClip" },
    saved: { type: "boolean" },
  }),
  NotmidChatRelationship: { type: "string", enum: ["friend", "non-friend"] },
  NotmidChatInviteStatus: {
    type: "string",
    enum: ["accepted", "pending-inbound", "pending-outbound", "rejected"],
  },
  NotmidChatAccess: objectSchema({
    relationship: { $ref: "#/components/schemas/NotmidChatRelationship" },
    inviteStatus: { $ref: "#/components/schemas/NotmidChatInviteStatus" },
    canSendMessage: { type: "boolean" },
    canAcceptInvite: { type: "boolean" },
    canRejectInvite: { type: "boolean" },
    reasonLabel: { type: "string" },
  }),
  NotmidThread: objectSchema({
    id: { type: "string" },
    title: { type: "string" },
    preview: { type: "string" },
    updatedAtLabel: { type: "string" },
    participantHandles: arrayOf({ type: "string" }),
    attachedPlaceId: { type: "string" },
    attachedClipId: { type: "string" },
    unreadCount: { type: "number" },
    chatAccess: { $ref: "#/components/schemas/NotmidChatAccess" },
  }),
  NotmidMessageAttachment: {
    oneOf: [
      objectSchema({ type: { const: "clip" }, clipId: { type: "string" } }),
      objectSchema({ type: { const: "place" }, placeId: { type: "string" } }),
      objectSchema({
        type: { const: "route" },
        title: { type: "string" },
        placeIds: arrayOf({ type: "string" }),
      }),
    ],
  },
  NotmidThreadMessage: objectSchema({
    id: { type: "string" },
    threadId: { type: "string" },
    senderHandle: { type: "string" },
    body: { type: "string" },
    createdAtLabel: { type: "string" },
    mine: { type: "boolean" },
    attachment: { $ref: "#/components/schemas/NotmidMessageAttachment" },
  }),
  NotmidThreadDetailResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    thread: { $ref: "#/components/schemas/NotmidThread" },
    messages: arrayOf({ $ref: "#/components/schemas/NotmidThreadMessage" }),
    attachedClip: { $ref: "#/components/schemas/NotmidClip" },
    attachedPlace: { $ref: "#/components/schemas/NotmidPlace" },
  }),
  NotmidSendThreadMessageRequest: objectSchema({
    body: { type: "string" },
    attachment: { $ref: "#/components/schemas/NotmidMessageAttachment" },
  }),
  NotmidStartThreadRequest: objectSchema({
    participantHandle: { type: "string" },
    body: { type: "string" },
    attachedClipId: { type: "string" },
    attachedPlaceId: { type: "string" },
  }),
  NotmidSendThreadMessageResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    message: { $ref: "#/components/schemas/NotmidThreadMessage" },
  }),
  NotmidChatInviteResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    thread: { $ref: "#/components/schemas/NotmidThread" },
  }),
  NotmidStartThreadResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    thread: { $ref: "#/components/schemas/NotmidThread" },
    message: { $ref: "#/components/schemas/NotmidThreadMessage" },
  }),
  NotmidCaptureDraft: objectSchema({
    id: { type: "string" },
    caption: { type: "string" },
    placeId: { type: "string" },
    moodTags: arrayOf({ type: "string" }),
    visibility: { $ref: "#/components/schemas/NotmidCaptureVisibility" },
    mediaState: { type: "string", enum: ["empty", "local-preview", "uploaded"] },
  }),
  NotmidCaptureDraftResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    draft: { $ref: "#/components/schemas/NotmidCaptureDraft" },
    candidatePlaces: arrayOf({ $ref: "#/components/schemas/NotmidPlace" }),
  }),
  NotmidCapturePublishRequest: objectSchema({
    draftId: { type: "string" },
    caption: { type: "string" },
    placeId: { type: "string" },
    moodTags: arrayOf({ type: "string" }),
    visibility: { $ref: "#/components/schemas/NotmidCaptureVisibility" },
  }),
  NotmidCapturePublishResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    clip: { $ref: "#/components/schemas/NotmidClip" },
    moderationStatus: { type: "string", enum: ["queued", "published"] },
  }),
  NotmidFeedResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    clips: arrayOf({ $ref: "#/components/schemas/NotmidClip" }),
    places: arrayOf({ $ref: "#/components/schemas/NotmidPlace" }),
  }),
  NotmidMapResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    places: arrayOf({ $ref: "#/components/schemas/NotmidPlace" }),
    highlightedClipIds: arrayOf({ type: "string" }),
  }),
  NotmidInboxResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    threads: arrayOf({ $ref: "#/components/schemas/NotmidThread" }),
  }),
  NotmidAuthUser: objectSchema({
    id: { type: "string" },
    handle: { type: "string" },
    displayName: { type: "string" },
    homeNeighborhood: { type: "string" },
    avatarImageUrl: { type: "string" },
    roles: arrayOf({ type: "string" }),
  }),
  NotmidProfilePrivacySettings: objectSchema({
    savedPlacesVisibility: { type: "string", enum: ["private"] },
    chatInvites: { type: "string", enum: ["shared-clips-and-places"] },
    defaultReceiptVisibility: { $ref: "#/components/schemas/NotmidCaptureVisibility" },
  }),
  NotmidProfileSettings: objectSchema({
    user: { $ref: "#/components/schemas/NotmidAuthUser" },
    privacy: { $ref: "#/components/schemas/NotmidProfilePrivacySettings" },
  }),
  NotmidProfileSettingsResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    settings: { $ref: "#/components/schemas/NotmidProfileSettings" },
  }),
  NotmidProfileSettingsUpdateRequest: objectSchema({
    displayName: { type: "string" },
    homeNeighborhood: { type: "string" },
  }),
  NotmidProfileSettingsUpdateResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    settings: { $ref: "#/components/schemas/NotmidProfileSettings" },
    updated: { type: "boolean" },
  }),
  NotmidAuthSession: objectSchema({
    accessToken: { type: "string" },
    provider: { $ref: "#/components/schemas/NotmidAuthProvider" },
    expiresAt: { type: "string" },
    user: { $ref: "#/components/schemas/NotmidAuthUser" },
  }),
  NotmidAuthStatusResponse: objectSchema({
    source: { $ref: "#/components/schemas/NotmidSource" },
    generatedAt: { type: "string" },
    mode: { $ref: "#/components/schemas/NotmidAuthMode" },
    authenticated: { type: "boolean" },
    user: { $ref: "#/components/schemas/NotmidAuthUser" },
    sessionExpiresAt: { type: "string" },
    requiredFor: arrayOf({ $ref: "#/components/schemas/NotmidAuthRequirement" }),
  }),
  NotmidSignInRequest: objectSchema({
    provider: { $ref: "#/components/schemas/NotmidAuthProvider" },
    intent: { $ref: "#/components/schemas/NotmidAuthIntent" },
    returnTo: { type: "string" },
  }),
  NotmidSignInResponse: objectSchema({
    mode: { $ref: "#/components/schemas/NotmidAuthMode" },
    session: { $ref: "#/components/schemas/NotmidAuthSession" },
    nextPath: { type: "string" },
  }),
  NotmidResolvedRoute: objectSchema({
    kind: { type: "string" },
    params: {
      type: "object",
      additionalProperties: { type: "string" },
    },
  }),
  NotmidResolvedRouteStack: objectSchema({
    canonicalPath: { type: "string" },
    stack: arrayOf({ $ref: "#/components/schemas/NotmidResolvedRoute" }),
  }),
  NotmidErrorResponse: objectSchema({
    error: objectSchema({
      code: { type: "string" },
      message: { type: "string" },
      requestId: { type: "string" },
    }),
  }),
} as const;
